### ISSUE TITLE
Error discovering MTU

### ISSUE THREAD

**Issue by gioiann** [Sandertv/go-raknet#3]
This happens randomly on different servers, this one in particular, on lbsg:

```
panic: error discovering MTU size: read udp myIP:46257->lbsgIP:19132: read: message too long
```

Also, the way the MTU is discovered (subtracting 40 to the size every 1/2 second) it's not the same way  minecraft itself does it. Minecraft only uses 3 MTU sizes: 1492, 1200, 576

**Comment by Sandertv** [comment]
6c06f8336a136b3235f95c929edf683489d797db should fix the error. For the way the MTU size is discovered, that's not really an issue, but I will consider changing that.

Please let me know if this commit fixes that issue.

**Comment by gioiann** [comment]
This was happening randomly just once in a while so i have no way to reproduce it. Unless you are sure it's fixed I guess only time will tell

**Comment by gioiann** [comment]
Still happens and when it happens, it happens in a row so i guess it's connection related

**Comment by Sandertv** [comment]
Unfortunately it seems like I cannot do anything about this. The 'message too long' is a syscall error that is simply out of control. I am not entirely sure what causes it.

**Comment by Sandertv** [comment]
Are you still having this issue?

**Comment by gioiann** [comment]
No. If it happens again I will let you know. I think this can be closed
